FROM php:fpm
WORKDIR /application/public
RUN apt-get update && apt-get install -y git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer require cinetpay/cinetpay-php
COPY . /application/public